// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:flutter_dotenv/flutter_dotenv.dart';
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Values from [android/app/google-services.json] (package `com.example.raunaq`) —
/// used when [.env] omits or mis-types keys. Keep in sync when you replace the JSON.
const String _gsAndroidApiKey =
    'AIzaSyCrOx_ROhHWZpGWRlmYFGF--vZkXNcGtw0';
const String _gsAndroidAppId =
    '1:447099267570:android:7fbdf21d45ac9e65ee636b';
const String _gsProjectId = 'mad-project-b0caf';
const String _gsSenderId = '447099267570';
const String _gsDatabaseUrl =
    'https://mad-project-b0caf-default-rtdb.firebaseio.com';
const String _gsStorageBucket = 'mad-project-b0caf.firebasestorage.app';

String _envOr(String key, String fallback) {
  final v = dotenv.env[key]?.trim();
  if (v != null && v.isNotEmpty) return v;
  return fallback;
}

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions web = FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_WEB_API_KEY'] ?? '',

    appId: dotenv.env['FIREBASE_WEB_APP_ID'] ?? '',

    messagingSenderId: dotenv.env['FIREBASE_SENDER_ID'] ?? '',

    projectId: dotenv.env['FIREBASE_PROJECT_ID'] ?? '',

    authDomain: dotenv.env['FIREBASE_AUTH_DOMAIN'] ?? '',

    databaseURL: dotenv.env['FIREBASE_DATABASE_URL'] ?? '',

    storageBucket: dotenv.env['FIREBASE_STORAGE_BUCKET'] ?? '',
  );

  static FirebaseOptions android = FirebaseOptions(
    apiKey: _envOr('FIREBASE_ANDROID_API_KEY', _gsAndroidApiKey),
    appId: _envOr('FIREBASE_ANDROID_APP_ID', _gsAndroidAppId),
    messagingSenderId: _envOr('FIREBASE_SENDER_ID', _gsSenderId),
    projectId: _envOr('FIREBASE_PROJECT_ID', _gsProjectId),
    databaseURL: _envOr('FIREBASE_DATABASE_URL', _gsDatabaseUrl),
    storageBucket: _envOr('FIREBASE_STORAGE_BUCKET', _gsStorageBucket),
  );

  static FirebaseOptions ios = FirebaseOptions(
    apiKey: _envOr('FIREBASE_ANDROID_API_KEY', _gsAndroidApiKey),
    appId: _envOr('FIREBASE_ANDROID_APP_ID', _gsAndroidAppId),
    messagingSenderId: _envOr('FIREBASE_SENDER_ID', _gsSenderId),
    projectId: _envOr('FIREBASE_PROJECT_ID', _gsProjectId),
    databaseURL: _envOr('FIREBASE_DATABASE_URL', _gsDatabaseUrl),
    storageBucket: _envOr('FIREBASE_STORAGE_BUCKET', _gsStorageBucket),
  );

  static FirebaseOptions macos = FirebaseOptions(
    apiKey: _envOr('FIREBASE_ANDROID_API_KEY', _gsAndroidApiKey),
    appId: _envOr('FIREBASE_ANDROID_APP_ID', _gsAndroidAppId),
    messagingSenderId: _envOr('FIREBASE_SENDER_ID', _gsSenderId),
    projectId: _envOr('FIREBASE_PROJECT_ID', _gsProjectId),
    databaseURL: _envOr('FIREBASE_DATABASE_URL', _gsDatabaseUrl),
    storageBucket: _envOr('FIREBASE_STORAGE_BUCKET', _gsStorageBucket),
  );

  static FirebaseOptions windows = FirebaseOptions(
    apiKey: _envOr('FIREBASE_ANDROID_API_KEY', _gsAndroidApiKey),
    appId: _envOr('FIREBASE_ANDROID_APP_ID', _gsAndroidAppId),
    messagingSenderId: _envOr('FIREBASE_SENDER_ID', _gsSenderId),
    projectId: _envOr('FIREBASE_PROJECT_ID', _gsProjectId),
    databaseURL: _envOr('FIREBASE_DATABASE_URL', _gsDatabaseUrl),
    storageBucket: _envOr('FIREBASE_STORAGE_BUCKET', _gsStorageBucket),
  );
}
