// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChw9rF6V-hwRbQpV_-q5_hPa5kE-JW3ik',
    appId: '1:447099267570:web:14c84282d0223403ee636b',
    messagingSenderId: '447099267570',
    projectId: 'mad-project-b0caf',
    authDomain: 'mad-project-b0caf.firebaseapp.com',
    storageBucket: 'mad-project-b0caf.firebasestorage.app',
    measurementId: 'G-PWV0FN231D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrOx_ROhHWZpGWRlmYFGF--vZkXNcGtw0',
    appId: '1:447099267570:android:7fbdf21d45ac9e65ee636b',
    messagingSenderId: '447099267570',
    projectId: 'mad-project-b0caf',
    storageBucket: 'mad-project-b0caf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnF52mcMXO8ZpT9fn3GkfdBR_rISvhDhg',
    appId: '1:447099267570:ios:f213c144cfbb8e8cee636b',
    messagingSenderId: '447099267570',
    projectId: 'mad-project-b0caf',
    storageBucket: 'mad-project-b0caf.firebasestorage.app',
    iosClientId: '447099267570-onev9o5hhtok3v6hl6bh69h18m4op9mr.apps.googleusercontent.com',
    iosBundleId: 'com.example.raunaq',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnF52mcMXO8ZpT9fn3GkfdBR_rISvhDhg',
    appId: '1:447099267570:ios:f213c144cfbb8e8cee636b',
    messagingSenderId: '447099267570',
    projectId: 'mad-project-b0caf',
    storageBucket: 'mad-project-b0caf.firebasestorage.app',
    iosClientId: '447099267570-onev9o5hhtok3v6hl6bh69h18m4op9mr.apps.googleusercontent.com',
    iosBundleId: 'com.example.raunaq',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyChw9rF6V-hwRbQpV_-q5_hPa5kE-JW3ik',
    appId: '1:447099267570:web:b1ef8360b8743fccee636b',
    messagingSenderId: '447099267570',
    projectId: 'mad-project-b0caf',
    authDomain: 'mad-project-b0caf.firebaseapp.com',
    storageBucket: 'mad-project-b0caf.firebasestorage.app',
    measurementId: 'G-XMBSDG7L2L',
  );
}
