// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPIFxqs7-gOxE-YEap0NRoQPtJHu_PxWg',
    appId: '1:803135336104:web:fb7180b4adb2217f8d5c9d',
    messagingSenderId: '803135336104',
    projectId: 'raunaq-3d044',
    authDomain: 'raunaq-3d044.firebaseapp.com',
    databaseURL: 'https://raunaq-3d044-default-rtdb.firebaseio.com',
    storageBucket: 'raunaq-3d044.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKI66hI0wQLnq9jrGcSUjoVTQJv1ZrGyA',
    appId: '1:803135336104:android:456e4a41e2909a9e8d5c9d',
    messagingSenderId: '803135336104',
    projectId: 'raunaq-3d044',
    databaseURL: 'https://raunaq-3d044-default-rtdb.firebaseio.com',
    storageBucket: 'raunaq-3d044.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKjjg3f4li7dsTpv_EotIcd1aZ4DaqeRA',
    appId: '1:803135336104:ios:1916492f8414dc8a8d5c9d',
    messagingSenderId: '803135336104',
    projectId: 'raunaq-3d044',
    databaseURL: 'https://raunaq-3d044-default-rtdb.firebaseio.com',
    storageBucket: 'raunaq-3d044.firebasestorage.app',
    iosBundleId: 'com.example.raunaq',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKjjg3f4li7dsTpv_EotIcd1aZ4DaqeRA',
    appId: '1:803135336104:ios:1916492f8414dc8a8d5c9d',
    messagingSenderId: '803135336104',
    projectId: 'raunaq-3d044',
    databaseURL: 'https://raunaq-3d044-default-rtdb.firebaseio.com',
    storageBucket: 'raunaq-3d044.firebasestorage.app',
    iosBundleId: 'com.example.raunaq',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAPIFxqs7-gOxE-YEap0NRoQPtJHu_PxWg',
    appId: '1:803135336104:web:d042b2a42ff7078b8d5c9d',
    messagingSenderId: '803135336104',
    projectId: 'raunaq-3d044',
    authDomain: 'raunaq-3d044.firebaseapp.com',
    databaseURL: 'https://raunaq-3d044-default-rtdb.firebaseio.com',
    storageBucket: 'raunaq-3d044.firebasestorage.app',
  );

}